Minilm
castorini/pygaggle pull request #204
Opened 2021-07-28 13:12 UTC by thiagolaitz

Adds miniLM support in evaluate_kaggle_highlighter.py and updates s.string to s.text in tokenize.py

2021-07-28 15:38 UTC, rodrigonogueira4 approved these changes
LGTM! @ronakice , could you please take a look and merge it once you are happy?

2021-08-01 10:25 UTC, ronakice requested changes
Two small comments, thanks for adding this! Once these have been addressed we can merge!

2021-08-01 10:25 UTC, ronakice commented on pygaggle/run/evaluate_kaggle_highlighter.py
>  from transformers import (AutoModel,
Can you move AutoModel to the next line?

2021-08-01 10:25 UTC, ronakice commented on pygaggle/run/evaluate_kaggle_highlighter.py
> +    if options.model != None:
```suggestion
    if options.model:
```

2021-08-24 20:50 UTC, ronakice commented on pygaggle/run/evaluate_kaggle_highlighter.py
>  from transformers import (AutoModel,
```suggestion
from transformers import (
AutoModel,
```

2021-08-24 20:52 UTC, ronakice commented on pygaggle/model/tokenize.py
>              document[:self.max_paragraph_length]).sents]
```suggestion
            document[:self.max_paragraph_length]).sents]
            
```

2021-08-24 20:54 UTC, ronakice approved these changes
Fixed some style stuff, merging!

2021-08-24 20:54 UTC, merged