Refactor fid reader
castorini/pygaggle pull request #257
Opened 2022-02-12 16:21 UTC by lingwei-gu

Notebook:
https://colab.research.google.com/drive/1DLX59bJvFjdv3wQM6wU0DDlcsaJzIAJ-#scrollTo=69zZa1KEPp5U

2022-02-12 16:25 UTC, ronakice requested changes
Add these for now I'll add more comments in a while

2022-02-12 16:44 UTC, lingwei-gu commented on pygaggle/qa/fid/model.py
> +# LICENSE file in the root directory of this source tree.
added the link to the license

2022-02-16 17:27 UTC, ronakice commented on pygaggle/qa/fid_reader.py
> +sys.path.insert(1, '/u0/o3liu/FiD')
what's this?

2022-02-16 17:28 UTC, ronakice commented on pygaggle/qa/fid_reader.py
> +        #     passage_ids, passage_masks = [], []
can we remove unnecessary comments?

2022-02-16 17:28 UTC, ronakice commented on pygaggle/qa/fid_reader.py
> +    print("main function executed")
just this in main?

2022-02-16 21:41 UTC, ronakice commented on pygaggle/run/evaluate_fid_ranker.py
> +READER_CHOICES = ('dpr', 'fid')
we don't need this choice here, since only fid exists.

2022-02-17 00:22 UTC, ronakice commented
Okay, thanks! Merging!

2022-02-17 00:23 UTC, ronakice approved these changes
LGTM!

2022-02-17 00:23 UTC, merged